version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81 #This could be done better.
    volumes: 
      - cache:/data
  web:
    build: .
    command: sh -c "python create_database.py && alembic upgrade head && uvicorn app:app --reload --port=8000 --host=0.0.0.0"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/learning_platform_development
      - REDIS_URL=redis://default:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@cache:6379/1 #This also...
    ports:
      - 8000:8000
    volumes:
      - .:/app
volumes:
  db:
    driver: local
  cache:
    driver: local